### ISSUE TITLE
Refactor the PipePistol into an organized scene

### ISSUE THREAD

**Issue by jonathandavidlewis** [loteque/pair-programming-jam-01#147]
Currently, the `PipePistol` is just a collection of nodes attached to the `PlayerController`. We are going to create new weapons soon. We should organize everything related to a weapon into a single scene, then use an instance of that scene in the `PlayerController`. This weapon, probably needs to go under something like `Equipment` or `Weapons` or `Attack` depending on what structure we are going for. As a start, `Attack` would work.

Having a separate node for the `Weapon` allows for the equipped `Weapon` to be separate from general `Attack` behavior of the `PlayerController` which may differ from behaviors of the specific `Weapon` being used.

## Todo

* [x] Refactor weapon behavior which is in the `PlayerController` Script into a single separate script, separate from the `PlayerController` script.
* [x] Organize all weapon-related nodes under this weapon node.
* [x] Extract this node into it's own scene.

```text
* PlayerController
  * Attack
    * PipePistol
```
